server:
  port: 8084

spring:
  application:
    name: estoque-service

  datasource:
    url: jdbc:postgresql://localhost:5432/estoque_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE